# Generated by Django 5.0.3 on 2024-04-07 23:45

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book_name",
                    models.CharField(max_length=100, verbose_name="Book Name"),
                ),
                (
                    "page_count",
                    models.IntegerField(null=True, verbose_name="Page Count"),
                ),
                ("category", models.CharField(max_length=100, verbose_name="Category")),
                (
                    "author",
                    models.CharField(max_length=100, null=True, verbose_name="Author"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Price"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=pathlib.PureWindowsPath("images"),
                        verbose_name="Image",
                    ),
                ),
            ],
            options={
                "db_table": "store_book",
            },
        ),
    ]
